Blog/companyblog/core/views.py
from flask import render_template,request,Blueprint,redirect
from companyblog.models import BlogPost, User
from companyblog.core.forms import TextGenForm
import requests
core = Blueprint('core',__name__)

@core.route('/')
def index():
    '''
    This is the home page view. Notice how it uses pagination to show a limited
    number of posts by limiting its query size and then calling paginate.
    '''
    users = User.query.all()
    return render_template('index.html', users=users)

@core.route('/info')
def info():
    '''
    Example view of any other "core" page. Such as a info page, about page,
    contact page. Any page that doesn't really sync with one of the models.
    '''
    return render_template('info.html')

Blog/companyblog/users/views.py
from flask import render_template ,url_for,flash,redirect,request,Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from companyblog import db
from companyblog.role_required import admin_required, not_ROLE
from companyblog.models import User, BlogPost, Post
from companyblog.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from companyblog.users.picture_handler import add_profile_pic


users = Blueprint('users',__name__)

# register

@users.route('/admin')
@admin_required
def view():
    return render_template('view.html')



@users.route('/register',methods=['GET','POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(
                    email=form.email.data,
                    username=form.username.data,
                    password=form.password.data,
                    role = 'base')

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registration!')
        return redirect(url_for('users.login'))

    return render_template('register.html',form=form)



# login
@users.route('/login',methods=['GET','POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:

            login_user(user)
            flash('Log in Success!')

            next = request.args.get('next')

            if next ==None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('login.html',form=form)


# logout
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))


# account (update UserForm)
@users.route('/account',methods=['GET','POST'])
@login_required
def account():

    form = UpdateUserForm()
    if form.validate_on_submit():

        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated!')
        return redirect(url_for('users.account'))

    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static',filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html',profile_image=profile_image,form=form)


@users.route('/stream',methods=['GET','POST'])
@login_required
def stream():
    user_entries = User.query.order_by(User.username).all()
    return render_template('stream.html', user=user_entries)    

Blog/companyblog/templates/account.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
  <div align='center'>
    <h1 >Welcome to the page for {{current_user.username}}</h1>
    <img align='center' src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image) }}">
    <p>{{ current_user.email }}</p>
  </div>
</div>
<div class="container">
  <form  method="POST" action="" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.username.label(class="form-group") }}
      {{form.username(class='form-control')  }}
    </div
    <div class="form-group">
      {{ form.email.label(class="form-group") }}
      {{form.email(class='form-control')  }}
    </div>
    <div class="form-group">
      {{ form.picture.label(class="form-group") }}
      {{ form.picture(class="form-control-file") }}
    </div>
    <div class="form-group">
        {{ form.submit(class="btn-primary") }}
    </div>
  </form>

</div>

{% endblock content %}

Blog/companyblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="./static/core_styles.css">
</head>
<body>


<ul class="nav">
  <a class="navbar-brand nav-text" href="{{url_for('core.index')}}">Navbar</a>

<li class="nav-link">
<a href="{{url_for('core.info')}}" class="nav-text">About</a>
</li>
{% if current_user.is_authenticated %}
<li class="nav-link">
<a href="{{url_for('users.logout')}}" class="nav-text" >Log Out</a>
</li>

<li class="nav-link">
<a href="{{url_for('users.account')}}" class="nav-text">Account</a>
</li>

<li class="nav-link">
  <a href="{{url_for('users.stream')}}" class="nav-text">Stream</a>
  </li>

{% else %}
<li class="nav-link">
<a href="{{url_for('users.login')}}" class="nav-text">Log In</a>
</li>

<li class="nav-link">
<a href="{{url_for('users.register')}}"  class="nav-text">Register</a>
</li>
{% endif %}
</ul>
 {% block content %}
 {% endblock %}
</div>
</body>
</html>

Blog/companyblog/templates/index.html
{% extends "base.html" %}
{% block content %}


<section style="margin-right: 25%;">
  <div class="jumbotron">
  <h1 class="landingh1">Welcome to LocalToken!</h1>
  <p>The first local business focused social media blockchain</p>
  </div>
    <div class="wave water"></div>
    <div class="wave water"></div>
    <div class="wave water"></div>
    <div class="wave water"></div>

</section>


<div class="container-explainer">
      <div class="left-text">
        <p>Lorem Ipsum Habble Gabble Grabbel madk Lorem Ipsum Habble Gabble Grabbel madk
          Lorem Ipsum Habble Gabble Grabbel madk Lorem Ipsum Habble Gabble Grabbel madk
          Lorem Ipsum Habble Gabble Grabbel madk
          Lorem Ipsum Habble Gabble Grabbel madk
        </p>
      </div>
      <div class="locationpic">
      
      </div>
</div>

{% endblock %}

Blog/companyblog/templates/info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Info</title>
</head>
<body>

{% extends "base.html" %}
{% block content %}

   <div class="jumbotron">
	<h1>Info about our company</h1>
	<p>Lorem Ipsum Text</p>
   </div>

{% endblock %}

</body>
</html>

Blog/companyblog/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
{% block content %}
<form method="POST">
{{form.hidden_tag()}}
{{form.email.label}}{{form.email}}<br>
{{form.password.label}}{{form.password}}<br>
{{form.submit()}}
</form>
{% endblock %}
</body>
</html>

Blog/companyblog/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
{% extends 'base.html' %}

{% block content %}
<div class="profile-options">
<input type="radio" name="choice-profiles" id="choice-profiles-business">
<label for="choice-profiles-business">Business</label>
<div class="reveal-if-active">

<aside class="biz-explainer"><h4>This is a profile that allows multiple employees to have different levels of control over the profile.</h4></aside>
<form class="registration" method="POST">
{{form.hidden_tag()}}
{{form.email.label}}{{form.email(class_="form-control")}}<br>
{{form.username.label}}{{form.username(class_="form-control")}}<br>
{{form.password.label}}{{form.password(class_="form-control")}}<br>
{{form.pass_confirm.label}}{{form.pass_confirm(class_="form-control")}}<br>
{{form.submit(class_="register-button")}}
</form>
</div>

<input type="radio" name="choice-profiles" id="choice-profiles-individual">
<label for="choice-profiles-individual">Individual</label>
<div class="reveal-if-active2">

<aside class="biz-explainer"><h4>This is an individual profile</h4></aside>
<form class="registration" method="POST">
{{form.hidden_tag()}}
{{form.email.label}}{{form.email(class_="form-control")}}<br>
{{form.username.label}}{{form.username(class_="form-control")}}<br>
{{form.password.label}}{{form.password(class_="form-control")}}<br>
{{form.pass_confirm.label}}{{form.pass_confirm(class_="form-control")}}<br>
{{form.submit(class_="register-button")}}
</form>
</div>
</div>

{% endblock %}
<script>
document.getElementById('choice-profiles-individual').checked = false;
</script>
</body>
</html>

Blog/companyblog/templates/stream.html
{% extends "base.html" %}
{% block content %}



<title>Infinite load</title>
</head>

<!-- sticky-top navbar displaying the counter -->
<nav class="navbar navbar-light bg-light sticky-top">
  <div class="container">
    <a class="navbar-brand" id="loaded" href="#">0 items loaded</a>
  </div>
</nav>

<body>

  <main class="mt-3">

    <div class="container">
      <div class="row">
        <div class="col">

          <h1 class="display-4 mb-3">Infinite load</h1>

          <!-- div to contain the content -->
          <div id="scroller" class="mb-3">

            <!-- template schema, hidden from the dom -->
            <template id="post_template">

              <!-- template content -->
              <div class="card mb-3 animated fadeIn shadow-sm">
                <div class="card-body">
                  <h4 class="card-title" id="title"></h4>
                  <span class="text-muted" id="content"></span>
                </div>
              </div>

            </template>

          </div>

          <!-- element to trigger the IntersectionObserver -->
          <div class="d-flex justify-content-center mb-3" id="sentinel">
            <div class="spinner-border" role="status"></div>
          </div>

        </div>
      </div>
    </div>

  </main>
<script>
    var scroller = document.querySelector("#scroller");
var template = document.querySelector('#post_template');
var loaded = document.querySelector("#loaded");
var sentinel = document.querySelector('#sentinel');

// Set a counter to count the items loaded
var counter = 0;

// Function to request new items and render to the dom
function loadItems() {

  // Use fetch to request data and pass the counter value in the QS
  fetch(`/load?c=${counter}`).then((response) => {

    // Convert the response data to JSON
    response.json().then((data) => {

      // If empty JSON, exit the function
      if (!data.length) {

        // Replace the spinner with "No more posts"
        sentinel.innerHTML = "No more posts";
        return;
      }

      // Iterate over the items in the response
      for (var i = 0; i < data.length; i++) {

        // Clone the HTML template
        let template_clone = template.content.cloneNode(true);

        // Query & update the template content
        template_clone.querySelector("#title").innerHTML = `${data[i][0]}: ${data[i][1]}`;
        template_clone.querySelector("#content").innerHTML = data[i][2];

        // Append template to dom
        scroller.appendChild(template_clone);

        // Increment the counter
        counter += 1;

        // Update the counter in the navbar
        loaded.innerText = `${counter} items loaded`;

      }
    })
  })
}

// Create a new IntersectionObserver instance
var intersectionObserver = new IntersectionObserver(entries => {

  // Uncomment below to see the entry.intersectionRatio when
  // the sentinel comes into view

  // entries.forEach(entry => {
  //   console.log(entry.intersectionRatio);
  // })

  // If intersectionRatio is 0, the sentinel is out of view
  // and we don't need to do anything. Exit the function
  if (entries[0].intersectionRatio <= 0) {
    return;
  }

  // Call the loadItems function
  loadItems();

});

// Instruct the IntersectionObserver to watch the sentinel
intersectionObserver.observe(sentinel);
</script>

{% endblock %}

Blog/companyblog/templates/view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% extends 'base.html' %}
<h1>Hello!</h1>
{% block content %}
{% endblock %}


</body>
</html>